export const mockContacts=[
    {
        firstName:"Ross",
        lastName:"Geller",
        email:"ross.geller@friends.com",
        phoneNumber:7821345332,
        status:"Active"
    },{
        firstName:"Rachel",
        lastName:"Greene",
        email:"rachel.greene@friends.com",
        phoneNumber:9823422253,
        status:"Active"
    },{
        firstName:"Monica",
        lastName:"Geller",
        email:"monica.geller@friends.com",
        phoneNumber:8432442241,
        status:"Active"
    },{
        firstName:"Chandler",
        lastName:"Bing",
        email:"chandler.bing@friends.com",
        phoneNumber:9932399848,
        status:"Inactive"
    },{
        firstName:"Phoebe",
        lastName:"buffay",
        email:"phoebe.buffay@friends.com",
        phoneNumber:9212183232,
        status:"Active"
    },{
        firstName:"Joey",
        lastName:"Tribbiani",
        email:"joey.tribbiani@friends.com",
        phoneNumber:8222293334,
        status:"Active"
    }
]